baseURL = "https://example.github.io/mcp-scope/"
languageCode = "en-us"
title = "ScopeCam MCP Documentation"
theme = "mcp-theme"
enableGitInfo = true
enableEmoji = true

# Enable robots.txt generation
enableRobotsTXT = true

# Syntax highlighting configuration
[markup.highlight]
  codeFences = true
  guessSyntax = true
  lineNos = true
  lineNumbersInTable = true
  tabWidth = 2

# Configure Markdown renderer
[markup.goldmark.renderer]
  unsafe = true # Allows HTML in Markdown

# Set permalinks structure
[permalinks]
  project = "/project/:filename/"
  guides = "/guides/:filename/"
  architecture = "/architecture/:filename/"
  standards = "/standards/:filename/"
  templates = "/templates/:filename/"
  mcp = "/mcp/:sections/:filename/"

# Define taxonomies
[taxonomies]
  tag = "tags"
  status = "status" 
  contributor = "contributors"

# Menu configuration
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
  
  [[menu.main]]
    name = "Project"
    url = "/project/"
    weight = 20

  [[menu.main]]
    name = "Architecture"
    url = "/architecture/"
    weight = 30

  [[menu.main]]
    name = "Guides"
    url = "/guides/"
    weight = 40

  [[menu.main]]
    name = "Standards"
    url = "/standards/"
    weight = 50

  [[menu.main]]
    name = "MCP"
    url = "/mcp/"
    weight = 60

# Parameters for theme and site functionality
[params]
  description = "Documentation for the ScopeCam Multi-Agent Control Platform"
  author = "ScopeCam Team"
  github_repo = "https://github.com/example/mcp-scope"
  github_branch = "main"
  
  # Status settings
  [params.status]
    active = "🟢 Active"
    draft = "🟡 Draft"
    review = "🟠 Review"
    outdated = "🔴 Outdated"
    archived = "⚫ Archived"
  
  # Layer configuration
  [params.layers]
    [params.layers.root]
      name = "Root Documentation"
      description = "Project-wide information and ScopeCam integration"
    
    [params.layers.mcp]
      name = "MCP Documentation"
      description = "Detailed implementation guides and technical information"