baseURL = "/"
languageCode = "en-us"
title = "ScopeCam MCP Documentation"

# Enable emoji and GitHub-style rendering
enableEmoji = true
enableGitInfo = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      # This is important for rendering HTML in markdown (required for badges)
      unsafe = true

[params]
  mainSections = ["docs", "architecture"]
  description = "Documentation for the Multi-Agent Control Platform (MCP) for ScopeCam Integration"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Documentation"
    url = "/docs/"
    weight = 2
  [[menu.main]]
    name = "Architecture"
    url = "/architecture/"
    weight = 3