baseURL = "https://example.github.io/mcp-scope/"
languageCode = "en-us"
title = "ScopeCam MCP Documentation"
theme = "mcp-theme"

# Enable Hugo features
enableGitInfo = true
enableRobotsTXT = true

# Default configurations
paginate = 10
summaryLength = 30

# Taxonomies
[taxonomies]
  tag = "tags"
  status = "status"
  contributor = "contributors"

# Author information
[author]
  name = "ScopeCam Team"

# Menu configuration
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "project"
    name = "Project"
    url = "/project/"
    weight = 2
  [[menu.main]]
    identifier = "guides"
    name = "Guides"
    url = "/guides/"
    weight = 3
  [[menu.main]]
    identifier = "architecture"
    name = "Architecture"
    url = "/architecture/"
    weight = 4
  [[menu.main]]
    identifier = "standards"
    name = "Standards"
    url = "/standards/"
    weight = 5
  [[menu.main]]
    identifier = "templates"
    name = "Templates"
    url = "/templates/"
    weight = 6
  [[menu.main]]
    identifier = "mcp"
    name = "MCP"
    url = "/mcp/"
    weight = 7

# Permalinks configuration
[permalinks]
  # Clean URLs without .html
  project = "/project/:filename/"
  guides = "/guides/:filename/"
  architecture = "/architecture/:filename/"
  standards = "/standards/:filename/"
  templates = "/templates/:filename/"
  mcp = "/mcp/:sections/:filename/"

# Site parameters
[params]
  # Site description
  description = "Documentation for the ScopeCam Multi-Agent Control Platform"
  
  # Copyright notice
  copyright = "© 2025 ScopeCam Team"
  
  # Documentation layers
  [params.layers]
    root_layer = "Root Documentation Layer"
    mcp_layer = "MCP Implementation Layer"
  
  # Status colors
  [params.status_colors]
    active = "#28a745"     # Green
    draft = "#ffc107"      # Yellow
    review = "#fd7e14"     # Orange
    outdated = "#dc3545"   # Red
    archived = "#343a40"   # Black
  
  # Social links
  [params.social]
    github = "https://github.com/example/mcp-scope"
  
  # Custom parameters
  [params.custom]
    show_status_in_lists = true
    enable_search = true
    enable_dark_mode = true
    show_toc = true
    enforce_front_matter = true

# Output formats
[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]
  page = ["HTML"]

# Markdown renderer options
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    lineNos = true
    lineNumbersInTable = true
    tabWidth = 2
  
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Allow HTML in Markdown
  
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2