baseURL = "https://verlyn13.github.io/mcp-scope/"
languageCode = "en-us"
title = "ScopeCam MCP Documentation"
theme = "mcp-theme"

# Enable syntax highlighting
pygmentsCodeFences = true
pygmentsStyle = "monokai"

# Enable Table of Contents for all pages by default
[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[params]
  # Theme color scheme
  colorScheme = "light" # or "dark", "auto"
  
  # Default documentation layer
  defaultLayer = "root" # or "mcp"
  
  # Navigation options
  showBreadcrumbs = true
  showToc = true
  tocDepth = 3
  
  # Status display options
  showStatus = true
  showUpdatedDate = true
  showContributors = true
  
  # Search options
  enableSearch = true
  searchMinLength = 3
  searchResultLength = 10