version: '3'

services:
  # Documentation site with Hugo
  docs:
    build:
      context: .
      dockerfile: Dockerfile.hugo
    ports:
      - "1313:1313"
    volumes:
      - .:/src:z
    environment:
      - HUGO_ENVIRONMENT=development
      - HUGO_BASEURL=http://localhost:1313/
    restart: unless-stopped

  # Core MCP Orchestrator
  mcp-core:
    build:
      context: ./mcp-project/mcp-core
      dockerfile: Dockerfile.dev
    volumes:
      - ./mcp-project/mcp-core:/app
      - ~/.gradle:/root/.gradle
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats

  # Messaging Bus (NATS for Agent Communication)
  nats:
    image: nats:latest
    ports:
      - "4222:4222"  # Client connections
      - "8222:8222"  # HTTP monitoring
    volumes:
      - ./mcp-project/nats/nats-server.conf:/etc/nats/nats-server.conf
    command: ["--config", "/etc/nats/nats-server.conf"]
    restart: unless-stopped

  # Camera Integration Agent with USB device passthrough
  camera-agent:
    build:
      context: ./mcp-project/agents/camera-agent
      dockerfile: Dockerfile.dev
    volumes:
      - ./mcp-project/agents/camera-agent:/app
    devices:
      - /dev/bus/usb:/dev/bus/usb  # USB device passthrough
    environment:
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats
      - mcp-core
    restart: unless-stopped

  # Optional: Python-based agent
  python-processor:
    build:
      context: ./mcp-project/agents/python-processor
      dockerfile: Dockerfile.python
    volumes:
      - ./mcp-project/agents/python-processor:/app
    environment:
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats
      - mcp-core
    restart: unless-stopped

networks:
  default:
    driver: bridge